<?php

namespace App\Models;

use App\Observers\MainCategoryObserver;
use Illuminate\Database\Eloquent\Model;

/**
 * @property integer $id
 * @property string $name
 * @property string $created_at
 * @property string $updated_at
 */
class MainCategory extends Model
{
    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        MainCategory::observe(MainCategoryObserver::class);
    }


    /**
     * @var array
     */
    protected $fillable = ['name', 'created_at', 'updated_at'];

}
