<?php

namespace App\Models;

use App\Observers\TaxObserver;
use Illuminate\Database\Eloquent\Model;

/**
 * @property integer $id
 * @property string $name
 * @property float $percentage
 * @property string $created_at
 * @property string $updated_at
 */
class Tax extends Model
{
    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        Tax::observe(TaxObserver::class);

    }

    /**
     * @var array
     */
    protected $fillable = ['name', 'percentage', 'created_at', 'updated_at'];

}
